{
    'name': 'sample_module',
    'version': '18.0.0.0',
    'summary': 'Training Module',
    'description': """This module is for training purposes.""",
    'category': 'Training',
    'author': 'shivakumar khot',
    'website': 'www.zbeanztech.com',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'sale',
        'sale_management',
        'account',
        'contacts',
        'product',
 
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/sequence.xml',
        'views/car_rental_view.xml',
        'views/food_view.xml',
        'views/model_one_view.xml',
        'views/model_one_lines.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
}
